//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidEarth2.Sdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluidEarth2.Sdk.HelpText", typeof(HelpText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = File Missing
        ///The file path cannot be resolved to a visible existing file. .
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Informative
        ///Additional information provided about current action..
        /// </summary>
        internal static string Informative {
            get {
                return ResourceManager.GetString("Informative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Instantiation
        ///Failed to create an object in memory from a specific Type..
        /// </summary>
        internal static string Instantiation {
            get {
                return ResourceManager.GetString("Instantiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Invalid AssemblyName
        ///Provided System.ReflectionAssemblyName is in wrong format..
        /// </summary>
        internal static string InvalidAssemblyName {
            get {
                return ResourceManager.GetString("InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Invalid OMI Argument Key
        ///Failed to resolve the supplied OMI Argument key attribute against any of the components Argument Id&apos;s..
        /// </summary>
        internal static string InvalidOmiArgumentKey {
            get {
                return ResourceManager.GetString("InvalidOmiArgumentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Invalid URI
        ///Provided URI is unresolvable..
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Set Argument.ValueAsString
        ///Failure to set argument value via ValueAsString method..
        /// </summary>
        internal static string SetArgumentValueAsString {
            get {
                return ResourceManager.GetString("SetArgumentValueAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = System.Exception
        ///A System.Exception has been thrown..
        /// </summary>
        internal static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = To Implement
        ///Requested action has not been implemented yet..
        /// </summary>
        internal static string ToImplement {
            get {
                return ResourceManager.GetString("ToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = XML Schema Validation
        ///Validation of XML against a schema..
        /// </summary>
        internal static string XmlSchemaValidation {
            get {
                return ResourceManager.GetString("XmlSchemaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = XML Schema Validation Event
        ///Validation of XML against a schema resulting in this event being triggered..
        /// </summary>
        internal static string XmlSchemaValidationEvent {
            get {
                return ResourceManager.GetString("XmlSchemaValidationEvent", resourceCulture);
            }
        }
    }
}
